<p>Restaurante universitário</p>
<b>Etapas: </b>
<ol>
    <li>Comprar ticket</li>
    <li>Entrar no restaurante (tomada decisão) ter ou não ter ticket</li>
    <li>Pegar bandeja</li>
    <li>Pegar comida (tomada de decisão) pegar comida ou não</li>
    <li>Entregar bandeja </li>
</ol>

<b>Descrição:</b> Inicialmente o Estudante precisa comprar ticket,após, a segunda etapa é a entrada
no restaurante onde o estudante passará ou não, caso não passe o estudante volta para a etapa
de compra de ticket, a terceira etapa é onde o estudante pega a bandeja, com a bandeja ele se serve
Caso queira comer mais o estudante pode voltar para a etapa de pegar comida caso não ele entrega a bandeja
e o processo se encerra.

In [19]:
import numpy as np
import pandas as pd

import random

In [25]:
n = 10

In [26]:
tempo_ultima_chegada = np.random.randint(0,50, n)

In [3]:
tempo_ultima_chegada

array([26, 41, 47, 35, 12,  3, 49, 38, 30, 43])

In [4]:
df = pd.DataFrame()

In [5]:
df["tempo_ultima_chegada"] = tempo_ultima_chegada

In [6]:
df

tempo_ultima_chegada
0                    26
1                    41
2                    47
3                    35
4                    12
5                     3
6                    49
7                    38
8                    30
9                    43

In [7]:
tempo_chegada = [np.sum(tempo_ultima_chegada[:i]) for i in range(1, len(tempo_ultima_chegada)+1)]

In [8]:
df["tempo_chegada"] = tempo_chegada

In [9]:
tempo_ultima_chegada

array([26, 41, 47, 35, 12,  3, 49, 38, 30, 43])

In [10]:
df

tempo_ultima_chegada  tempo_chegada
0                    26             26
1                    41             67
2                    47            114
3                    35            149
4                    12            161
5                     3            164
6                    49            213
7                    38            251
8                    30            281
9                    43            324

In [39]:
tempo_ticket = np.random.randint(0, 100, n)

In [36]:
tempo_ticket[tempo_ticket > 20] = 0

In [40]:
tempo_ticket

array([63, 46, 67, 85, 75, 94, 69, 90, 21, 64])